/* Generated by `pnpm schema:generate`. Do not edit directly. */
import type {
  ComponentNode,
  ContentReference,
  RichTextDocument,
  AssetReference,
} from '@gridstory/schema';

export interface PageContent {
  title: string;
  slug: string;
  story?: RichTextDocument;
  socialImage?: AssetReference;
  relatedPages?: ContentReference[];
  topics?: string[];
  blocks: ComponentNode[];
}

export interface ArticleContent {
  headline: string;
  slug: string;
  summary?: string;
  body: RichTextDocument;
  relatedPages?: ContentReference[];
  topics?: string[];
  featured?: boolean;
}

export interface NavigationMenuNavigationMenuItemObject {
  id: string;
  parentId?: string;
  label: string;
  kind: 'internal' | 'external';
  target?: ContentReference;
  externalUrl?: string;
}

export interface NavigationMenuContent {
  key: string;
  name: string;
  items: Array<NavigationMenuNavigationMenuItemObject>;
}

export interface GridstoryHeroProps {
  eyebrow?: string;
  heading: string;
  body: string;
  tone: 'indigo' | 'sunrise' | 'forest';
}

export type GridstoryHeroSlots = Record<string, never>;

export interface GridstoryRichTextProps {
  heading: string;
  body: string;
}

export type GridstoryRichTextSlots = Record<string, never>;

export interface GridstoryCalloutProps {
  heading: string;
  body: string;
  tone: 'info' | 'success' | 'warning';
}

export type GridstoryCalloutSlots = Record<string, never>;

export interface GridstoryStackProps {
  gap: 'small' | 'medium' | 'large';
  surface: 'plain' | 'subtle' | 'contrast';
}

export interface GridstoryStackSlots {
  content?: ComponentNode[];
}

export interface ContentByType {
  page: PageContent;
  article: ArticleContent;
  'navigation-menu': NavigationMenuContent;
}

export interface ComponentPropsById {
  'gridstory.hero': GridstoryHeroProps;
  'gridstory.rich-text': GridstoryRichTextProps;
  'gridstory.callout': GridstoryCalloutProps;
  'gridstory.stack': GridstoryStackProps;
}
