import { z } from 'zod';

/**
 * Reviewed application limits and benchmark profile for the M5-007 support boundary.
 * Keep this object JSON-serializable so release tooling can publish it verbatim.
 */
export const resourceLimits = {
  version: 1,
  api: {
    ordinaryBodyBytes: 1_048_576,
    assetPartBodyBytes: 5_242_880,
    portabilityImportBodyBytes: 16_777_216,
  },
  assets: {
    maximumBytes: 100_000_000,
    maximumDimensionPixels: 16_384,
    maximumParts: 1_000,
  },
  portability: {
    maximumEntries: 1_000,
    maximumRevisionsPerEntry: 100,
    maximumAuditEventsPerEntry: 1_000,
  },
  graphql: {
    maximumDepth: 12,
    maximumAliases: 50,
    maximumFieldSelections: 500,
    batching: false,
    subscriptions: false,
  },
  contentQuery: {
    maximumPageSize: 100,
    maximumFilterDepth: 8,
    maximumBooleanGroupSize: 25,
    maximumPredicates: 50,
    maximumSetValues: 100,
    maximumSortFields: 5,
    maximumProjectionFields: 50,
    maximumPathCharacters: 200,
  },
  search: {
    maximumTextCharacters: 500,
    maximumContentTypes: 50,
    maximumRequestedResults: 100,
    maximumReturnedResults: 50,
    maximumTraversalDepth: 12,
    maximumIndexedStringsPerEntry: 5_000,
    maximumIndexedTextCharacters: 100_000,
  },
  operations: {
    maximumListPageSize: 1_000,
    maximumDrainBatch: 100,
    outboxDeadAfterAttempts: 10,
    maximumJobAttempts: 20,
  },
  plugins: {
    maximumArtifactBytes: 100_000_000,
    defaultInvocationsPerMinutePerScope: 60,
    defaultInvocationTimeoutMs: 5_000,
    defaultInputBytes: 65_536,
    defaultOutputBytes: 262_144,
  },
  governance: {
    maximumRetentionRules: 1_000,
    maximumPlanCandidates: 10_000,
    maximumExecutionBatch: 100,
    maximumExportResources: 10_000,
    maximumReauthenticationAgeSeconds: 900,
    maximumBackupEvidenceAgeSeconds: 86_400,
  },
  migration: {
    maximumSources: 50,
    maximumProjects: 50,
    maximumRecipes: 100,
    maximumFieldMappingsPerRecipe: 100,
    maximumSourceRecordsPerRun: 1_000,
    maximumSourceResponseBytes: 8_388_608,
    maximumStoredPlans: 20,
    maximumStoredRuns: 100,
    planLifetimeSeconds: 3_600,
  },
  marketplace: {
    maximumPublishers: 100,
    maximumReleases: 500,
    maximumReviewRunsPerRelease: 20,
    maximumReviewChecks: 50,
    maximumKeywords: 20,
    maximumTestedRuntimes: 20,
    publisherChallengeLifetimeSeconds: 900,
    maximumReviewEvidenceAgeSeconds: 604_800,
  },
  personalization: {
    maximumPurposes: 25,
    maximumAttributes: 50,
    maximumAttributeValues: 100,
    maximumAudiences: 100,
    maximumConditionsPerAudience: 20,
    maximumDecisions: 100,
    maximumVariantsPerDecision: 20,
    maximumRulesPerDecision: 100,
    maximumContextAttributes: 50,
    maximumExperiments: 50,
    maximumExperimentVariants: 10,
    maximumExperimentMetrics: 20,
    maximumExperimentSnapshots: 100,
    maximumExperimentGuardrailReasons: 25,
  },
  analytics: {
    maximumAdapters: 20,
    maximumContentMetrics: 1_000,
    maximumComponentMetrics: 1_000,
    maximumInteractionNamesPerComponent: 25,
    maximumReleaseAnnotations: 100,
    maximumIdempotencyReceipts: 5_000,
    maximumEventAgeSeconds: 86_400,
    maximumFutureSkewSeconds: 300,
  },
  aiGateway: {
    maximumModels: 50,
    maximumPromptVersions: 200,
    maximumActivePrompts: 50,
    maximumAllowedModelsPerPrompt: 20,
    maximumRetrievalRulesPerPrompt: 50,
    maximumFieldsPerRetrievalRule: 50,
    maximumSourcesPerRequest: 20,
    maximumInputCharacters: 10_000,
    maximumInstructionCharacters: 20_000,
    maximumSourceCharacters: 50_000,
    maximumOutputCharacters: 50_000,
    maximumDailyUsageRecords: 31,
    maximumRequestReceipts: 1_000,
    maximumStateEvents: 200,
    minimumTimeoutMs: 100,
    maximumTimeoutMs: 120_000,
  },
  aiAuthoring: {
    maximumActions: 50,
    maximumTargetFieldsPerAction: 20,
    maximumEvaluationRulesPerAction: 50,
    maximumProposals: 1_000,
    maximumChangesPerProposal: 20,
    maximumSuggestedValueCharacters: 20_000,
    maximumRationaleCharacters: 2_000,
    maximumReviewReasonCharacters: 1_000,
    maximumEvaluationMessageCharacters: 500,
    maximumSemanticRules: 50,
    maximumSemanticFieldsPerRule: 20,
    maximumSemanticQueryCharacters: 1_000,
    maximumSemanticResults: 50,
    maximumSemanticAdapterHits: 100,
    maximumSemanticSourceCharacters: 50_000,
  },
  regional: {
    maximumReadRegions: 20,
    maximumEntriesPerRead: 1_000,
    maximumOperations: 100,
    maximumLagMs: 86_400_000,
    maximumDataLossMs: 604_800_000,
    maximumFutureSkewMs: 30_000,
    planLifetimeSeconds: 900,
    maximumReauthenticationAgeSeconds: 900,
    maximumBackupEvidenceAgeSeconds: 86_400,
  },
  contentFederation: {
    maximumOffers: 50,
    maximumAgreements: 50,
    maximumTypesPerOffer: 50,
    maximumRecordsPerSnapshot: 1_000,
    maximumEnvelopeBytes: 8_388_608,
    maximumPlans: 20,
    maximumReceipts: 100,
    maximumAttributedAgents: 20,
    maximumFutureSkewMs: 30_000,
    envelopeLifetimeSeconds: 300,
    planLifetimeSeconds: 900,
  },
  knowledge: {
    maximumSeedEntries: 10,
    maximumSourceEntries: 1_000,
    maximumTraversalDepth: 3,
    maximumGraphNodes: 200,
    maximumGraphEdges: 500,
    maximumGraphPaths: 200,
    maximumRecommendations: 50,
    maximumContributionsPerRecommendation: 20,
    maximumAgentPolicies: 50,
    maximumAgentTools: 3,
    maximumAgentToolCalls: 10,
    maximumAgentToolResultBytes: 262_144,
    maximumAgentGoalCharacters: 4_000,
    maximumAgentPlans: 100,
    maximumAgentReceipts: 100,
    maximumAgentChanges: 20,
    maximumAgentChangeCharacters: 20_000,
    minimumAgentTimeoutMs: 100,
    maximumAgentTimeoutMs: 120_000,
    maximumPlanLifetimeSeconds: 900,
  },
  benchmark: {
    datasetEntries: 250,
    readSamples: 120,
    writeSamples: 30,
    concurrency: 8,
    maximumPeakResidentMemoryBytes: 536_870_912,
    sqlite: {
      maximumReadP95Ms: 100,
      maximumQueryP95Ms: 250,
      maximumWriteP95Ms: 250,
      minimumReadThroughputPerSecond: 25,
    },
    postgres: {
      maximumReadP95Ms: 150,
      maximumQueryP95Ms: 350,
      maximumWriteP95Ms: 350,
      minimumReadThroughputPerSecond: 20,
    },
  },
} as const;

export type GridStoryResourceLimits = typeof resourceLimits;

const benchmarkMetricSchema = z.object({
  samples: z.number().int().positive(),
  p50Ms: z.number().nonnegative(),
  p95Ms: z.number().nonnegative(),
  p99Ms: z.number().nonnegative(),
  throughputPerSecond: z.number().positive(),
});

export const benchmarkReportSchema = z.object({
  schemaVersion: z.literal(1),
  profile: z.enum(['sqlite', 'postgres']),
  generatedAt: z.string().datetime(),
  environment: z.object({
    node: z.string().min(1),
    platform: z.string().min(1),
    architecture: z.string().min(1),
    availableParallelism: z.number().int().positive(),
    totalMemoryBytes: z.number().int().positive(),
  }),
  dataset: z.object({
    entries: z.number().int().positive(),
    tenantId: z.string().min(1),
    transport: z.literal('fastify-inject'),
  }),
  scenarios: z
    .array(
      z.object({
        name: z.string().min(1),
        category: z.enum(['read', 'query', 'write']),
        metrics: benchmarkMetricSchema,
        maximumP95Ms: z.number().positive(),
        minimumThroughputPerSecond: z.number().positive().optional(),
        passed: z.boolean(),
      }),
    )
    .min(4),
  peakResidentMemoryBytes: z.number().int().positive(),
  maximumPeakResidentMemoryBytes: z.number().int().positive(),
  passed: z.boolean(),
  claimBoundary: z.string().min(40),
});

export type BenchmarkReport = z.infer<typeof benchmarkReportSchema>;
